# Generated by Django 5.0.1 on 2025-11-20 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("invoice_id", models.CharField(editable=False, max_length=20, unique=True)),
                ("business_name", models.CharField(max_length=200)),
                ("business_email", models.EmailField(max_length=254)),
                ("business_phone", models.CharField(blank=True, max_length=50)),
                ("business_address", models.TextField()),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(max_length=254)),
                ("client_phone", models.CharField(blank=True, max_length=50)),
                ("client_address", models.TextField()),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("NGN", "Nigerian Naira"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("brand_name", models.CharField(blank=True, max_length=100)),
                ("brand_color", models.CharField(default="#6366f1", max_length=7)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
    ]
