# Generated by Django 5.2.8 on 2025-11-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoice_user_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoice_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoice_user_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoice_id_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoice_user_client_idx",
        ),
    ]
