# Generated by Django 5.2.8 on 2025-11-22 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_invoice_user_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'invoice_date'], name='idx_user_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_id'], name='idx_invoice_id'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'client_email'], name='idx_user_client'),
        ),
    ]
