# Generated by Django 5.2.8 on 2025-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_add_recurring_templates_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('feature', models.CharField(choices=[('templates', 'Invoice Templates'), ('api', 'API Access'), ('general', 'General Updates')], default='general', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
