# Generated by Django 5.2.9 on 2025-12-09 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_add_social_account_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_contact_status'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email'], name='idx_contact_email'),
        ),
        migrations.AddIndex(
            model_name='invoicetemplate',
            index=models.Index(fields=['user', 'is_default'], name='idx_template_user_default'),
        ),
        migrations.AddIndex(
            model_name='lineitem',
            index=models.Index(fields=['invoice'], name='idx_lineitem_invoice'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['user', 'status'], name='idx_recurring_user_status'),
        ),
        migrations.AddIndex(
            model_name='recurringinvoice',
            index=models.Index(fields=['status', 'next_generation'], name='idx_recurring_schedule'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['feature', 'is_notified'], name='idx_waitlist_feature'),
        ),
    ]
