# Generated by Django 5.2.9 on 2025-12-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Preserved in case user is deleted', max_length=254)),
                ('user_username', models.CharField(help_text='Preserved in case user is deleted', max_length=150)),
                ('request_type', models.CharField(choices=[('data_export', 'Data Export (Article 20)'), ('data_deletion', 'Data Deletion (Article 17)'), ('subject_access', 'Subject Access Request (Article 15)'), ('rectification', 'Rectification (Article 16)'), ('restriction', 'Restriction (Article 18)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional request details from user')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for processing')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, help_text='Error message if email delivery failed')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GDPR Request',
                'verbose_name_plural': 'GDPR Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='lineitem',
            name='idx_lineitem_invoice',
        ),
        migrations.AddField(
            model_name='gdprrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_requests_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gdprrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gdprrequest',
            index=models.Index(fields=['status', '-requested_at'], name='idx_gdpr_status'),
        ),
        migrations.AddIndex(
            model_name='gdprrequest',
            index=models.Index(fields=['request_type', '-requested_at'], name='idx_gdpr_type'),
        ),
        migrations.AddIndex(
            model_name='gdprrequest',
            index=models.Index(fields=['user_email'], name='idx_gdpr_email'),
        ),
    ]
